sudo su
 
sudo apt update
 
sudo apt install docker.io docker-compose
 
docker
 
pwd
 
mkdir dockercom
 
cd dockercomp
 
vim windowsto2.yaml
 
 
----------------------------------------------------
 
 
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"
      USERNAME: "TOOLBOXLAP"
      PASSWORD: "aDmin@123"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "990G"
      DISK2_SIZE: "101G"
    devices:         
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
 
-------------------------------------------------------
 
cat windowsto2.yaml
 
sudo docker-compose -f windowsto2.yaml up             
 
 
---------------------------------------كود اعاده التشغيل --------------------------------------
sudo docker-compose -f windowsto2.yaml up                          New-Item -ItemType Directory -Path $startupPath -Force | Out-Null
                      }

                      Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath -UseBasicParsing
                      Write-Host "✅ Downloads.bat copied to $downloadPath"

                      # Run the batch file for the first time
                      cmd /c $downloadPath
                      Write-Host "✅ Downloads.bat executed successfully"
                      break
                  }
                  catch {
                      Write-Host "❌ Error copying or executing Downloads.bat: $($_.Exception.Message)"
                      break
                  }
              }
              else {
                  Write-Host "[$(Get-Date)] Waiting for RDP profile to be created..."
                  Start-Sleep -Seconds 30
              }
          }

          # Keep runner alive
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
